repos:
-   repo: local
    hooks:
      - id: pytest
        name: Kör tester med Pytest
        entry: pytest
        language: python
        pass_filenames: false
        stages: [pre-commit]

      - id: behave
        name: Kör tester med Behave
        entry: behave
        language: python
        pass_filenames: false
        stages: [pre-commit]

      - id: flake8
        name: Kör tester med Flake8
        entry: flake8 src features tests
        language: python
        pass_filenames: false
        stages: [pre-commit]
